---
kind: pipeline
type: docker
name: default

steps:
  - name: tests
    image: node:alpine
    commands:
      - npm ci
      - npm run test

  - name: publish
    image: plugins/docker
    settings:
      tags: latest
      repo: securetdrone/drone-yc-database
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
